env: "local"
storage_path: "../../storage/sso.db"
grpc:
  port: 44044
  timeout: 10h
verification:
  len: 6
  hours: 3
emailSender:
  name: "Cyril Firsov"
  email: "kifirigor@gmail.com"
  password: "ahvi kyzn wdqj ueyr"